name: Lookup Hosts
on:
  schedule:
    - cron: "0 0 * * *" # 每天的 UTC 时间 0 点触发
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

jobs:
  lookup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun ./lookup.ts
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add candidates.json
          git commit -m 'Update candidates JSON'
          git push origin main
